postgres-data:
  image: busybox
  volumes:
    - /var/lib/postgresql/lg-data
  container_name: lg-posgres-datastore


postgresql:
  image: postgres
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password
  ports:
    - "5432:5432"
  volumes_from:
    - postgres-data
